name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm run test
