name: 'Create Release'
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true
        default: 'v0.0.0'

permissions:
  contents: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Consts.ts version
      run: |
        sed -ri "s/ Version = '(v[0-9]+.[0-9]+.[0-9]+)';/ Version = '${{ github.event.inputs.new_version }}';/g" src/types/consts.ts
    - name: Update package.json version
      run: |
        sed -ri '3s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package.json
    - name: Update package-lock.json version
      run: |
        sed -ri '3s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package-lock.json
        sed -ri '9s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package-lock.json
    - name: Commit changes
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -a -m 'version ${{ github.event.inputs.new_version }}'
        git push
        echo "Success"
    - name: Create Tag
      run: |
        git tag -a -m 'version ${{ github.event.inputs.new_version }}' ${{ github.event.inputs.new_version }}
        git push origin ${{ github.event.inputs.new_version }}
        echo "Complete"
  build_release:
    needs: bump_version
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Release Environment (Consts.ts)
      run: |
        sed -i "s/ Dev = true;/ Dev = false;/g" src/types/consts.ts
    - name: Set Release Environment (rollup.config.js)
      run: |
        sed -i "s/var dev = true;/var dev = false;/g" rollup.config.js
    - name: Install modules
      run: yarn
    - name: Run build
      run: yarn build
    - name: Release
      uses: mikepenz/action-gh-release@v0.4.0
      with:
        body: |
          ![Downloads](https://img.shields.io/github/downloads/gh61/lovelace-hue-like-light-card/${{ github.ref }}/total)


        draft: true
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: release/hue-like-light-card.js