name: 'Create Release'
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true
        default: 'v0.0.0'

permissions:
  contents: write

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update Consts.ts version
      run: |
        sed -ri "s/ Version = '(v[0-9]+.[0-9]+.[0-9]+)';/ Version = '${{ github.event.inputs.new_version }}';/g" src/types/consts.ts
    - name: Update package.json version
      run: |
        sed -ri '3s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package.json
    - name: Update package-lock.json version
      run: |
        sed -ri '3s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package-lock.json
        sed -ri '9s/"version": "(v[0-9]+.[0-9]+.[0-9]+)"/"version": "${{ github.event.inputs.new_version }}"/g' package-lock.json
    - name: Commit changes
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -a -m 'version ${{ github.event.inputs.new_version }}'
        git push
        echo "Success"
    - name: Create Tag
      run: |
        git tag -a -m 'version ${{ github.event.inputs.new_version }}' ${{ github.event.inputs.new_version }}
        git push origin ${{ github.event.inputs.new_version }}
        echo "Complete"
  build_release:
    needs: bump_version
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main # without this, the latest commit (version change) isn't fetched
    - name: Fetch tags # we need to fetch tags for issues_changelog generator
      run: |
        git fetch -t
    - name: Set Release Environment (Consts.ts)
      run: |
        sed -i "s/ Dev = true;/ Dev = false;/g" src/types/consts.ts
    - name: Set Release Environment (rollup.config.mjs)
      run: |
        sed -i "s/var dev = true;/var dev = false;/g" rollup.config.mjs

    - uses: actions/setup-node@v4
    - name: Install modules
      run: npm ci
    - name: Run build
      run: npm run build

    - name: Generate changelog
      id: commits_changelog
      uses: jaywcjlove/changelog-generator@v2.1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filter: '(version\s+[v|V]\d(\.\d+){0,2}|[m|M]erge\s|\(\#\d+\):)'
        template: |
          ## Features 🌟
          {{feat}}
          ## Fixed bugs 🐞
          {{fix}}
          ## Improved 📈
          {{refactor,perf,clean,type}}
          ## Documentation 📖
          {{doc}}
          ## Misc 💢
          {{chore,style,ci,build,test||🔶 Nothing changed}}
          ## Unknown
          {{__unknown__}}

    - name: Generate Issues Changelog
      id: issues_changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.3 # version 2.4 creates malformed changelog
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        onlyLastTag: true
        pullRequests: false
        simpleList: true
        compareLink: false
        #unreleasedOnly: true # only unreleased issues - IS FAILING
        stripHeaders: true
        stripGeneratorNotice: true

    - name: Release
      uses: mikepenz/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.new_version }}
        draft: true
        files: release/hue-like-light-card.js
        fail_on_unmatched_files: true
        body: |
          ![Downloads](https://img.shields.io/github/downloads/gh61/lovelace-hue-like-light-card/${{ github.event.inputs.new_version }}/total)

          ## Closed Issues 🚩
          ${{ steps.issues_changelog.outputs.changelog }}

          ${{ steps.commits_changelog.outputs.changelog }}

          **Compare**: ${{ steps.commits_changelog.outputs.compareurl }}
        generate_release_notes: false
