name: Create New version Tag
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true
        default: 'v0.0.0'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update Consts.ts version
      run: |
        sed -ri "s/ Version = '(v[0-9]+.[0-9]+.[0-9])';/ Version = '${{ github.event.inputs.new_version }}';/g" src/types/consts.ts
    - name: Update package.json version
      run: |
        sed -ri 's/"version": "(v[0-9]+.[0-9]+.[0-9])"/"version": "${{ github.event.inputs.new_version }}"/g' package.json
    - name: Commit changes
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -a -m 'version ${{ github.event.inputs.new_version }}'
        git tag -a -m 'version ${{ github.event.inputs.new_version }}' ${{ github.event.inputs.new_version }}
# git push origin ${{ github.event.inputs.new_version }}
# echo "Complete"